
export const testAction = {
  TEST_REQUEST: 'test/TEST_REQUEST',
  TEST_SUCCESS: 'test/TEST_SUCCESS',
  TEST_FAILURE: 'test/TEST_FAILURE',
}

export interface BaseAction {
  type: string;
  payload: any;
}

export const authAction = {
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
}

export const ADAuthAction = {
  AUTHENTICATION_START: 'AUTHENTICATION_START',
  AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
  AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
}

export const getMyAccountAction = {
  GET_MY_ACCOUNT_REQUEST: 'GET_MY_ACCOUNT_REQUEST',
  GET_MY_ACCOUNT_SUCCESS: 'GET_MY_ACCOUNT_SUCCESS',
  GET_MY_ACCOUNT_FAILURE: 'GET_MY_ACCOUNT_FAILURE',
}

export const UsersAction = {
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
}

export const mapTableHoverAction = {
  MAP_TABLE_HOVER_START: 'MAP_TABLE_HOVER_START',
  MAP_TABLE_HOVER_DOING: 'MAP_TABLE_HOVER_DOING',
  MAP_TABLE_HOVER_FAILURE: 'MAP_TABLE_HOVER_FAILURE',
}

export const InviteUserAction = {
  INVITE_USER_REQUEST: 'INVITE_USER_REQUEST',
  INVITE_USER_SUCCESS: 'INVITE_USER_SUCCESS',
  INVITE_USER_FAILURE: 'INVITE_USER_FAILURE',
}

export const BrandsAction = {
  GET_BRANDS_REQUEST: 'GET_BRANDS_REQUEST',
  GET_BRANDS_SUCCESS: 'GET_BRANDS_SUCCESS',
  GET_BRANDS_FAILURE: 'GET_BRANDS_FAILURE',

  GET_BRAND_BY_ID_REQUEST: 'GET_BRAND_BY_ID_REQUEST',
  GET_BRAND_BY_ID_SUCCESS: 'GET_BRAND_BY_ID_SUCCESS',
  GET_BRAND_BY_ID_FAILURE: 'GET_BRAND_BY_ID_FAILURE',
}

export const LookupAction = {
  GET_LOOKUP_REQUEST: 'GET_LOOKUP_REQUEST',
  GET_LOOKUP_SUCCESS: 'GET_LOOKUP_SUCCESS',
  GET_LOOKUP_FAILURE: 'GET_LOOKUP_FAILURE',

  GET_LOOKUP_BY_FILTER_REQUEST: 'GET_LOOKUP_BY_FILTER_REQUEST',
  GET_LOOKUP_BY_FILTER_SUCCESS: 'GET_LOOKUP_BY_FILTER_SUCCESS',
  GET_LOOKUP_BY_FILTER_FAILURE: 'GET_LOOKUP_BY_FILTER_FAILURE',
}

// Website
export const WebsiteSummaryAction = {
  GET_WEBSITE_SUMMARY_REQUEST: 'GET_WEBSITE_SUMMARY_REQUEST',
  GET_WEBSITE_SUMMARY_SUCCESS: 'GET_WEBSITE_SUMMARY_SUCCESS',
  GET_WEBSITE_SUMMARY_FAILURE: 'GET_WEBSITE_SUMMARY_FAILURE',
} 

export const WebsiteBehaviourChannelsAction = {
  GET_WEBSITE_BEHAVIOUR_CHANNELS_REQUEST: 'GET_WEBSITE_BEHAVIOUR_CHANNELS_REQUEST',
  GET_WEBSITE_BEHAVIOUR_CHANNELS_SUCCESS: 'GET_WEBSITE_BEHAVIOUR_CHANNELS_SUCCESS',
  GET_WEBSITE_BEHAVIOUR_CHANNELS_FAILURE: 'GET_WEBSITE_BEHAVIOUR_CHANNELS_FAILURE',
}

export const WebsiteBehaviourTimelineAction = {
  GET_WEBSITE_BEHAVIOUR_TIMELINE_REQUEST: 'GET_WEBSITE_BEHAVIOUR_TIMELINES_REQUEST',
  GET_WEBSITE_BEHAVIOUR_TIMELINE_SUCCESS: 'GET_WEBSITE_BEHAVIOUR_TIMELINES_SUCCESS',
  GET_WEBSITE_BEHAVIOUR_TIMELINE_FAILURE: 'GET_WEBSITE_BEHAVIOUR_TIMELINES_FAILURE',
}

export const WebsiteTransactionsSummaryAction = {
  GET_WEBSITE_TRANSACTIONS_SUMMARY_REQUEST: 'GET_WEBSITE_TRANSACTIONS_SUMMARY_REQUEST',
  GET_WEBSITE_TRANSACTIONS_SUMMARY_SUCCESS: 'GET_WEBSITE_TRANSACTIONS_SUMMARY_SUCCESS',
  GET_WEBSITE_TRANSACTIONS_SUMMARY_FAILURE: 'GET_WEBSITE_TRANSACTIONS_SUMMARY_FAILURE',
} 

export const WebsiteTransactionsTimelineAction = {
  GET_WEBSITE_TRANSACTIONS_TIMELINE_REQUEST: 'GET_WEBSITE_TRANSACTIONS_TIMELINE_REQUEST',
  GET_WEBSITE_TRANSACTIONS_TIMELINE_SUCCESS: 'GET_WEBSITE_TRANSACTIONS_TIMELINE_SUCCESS',
  GET_WEBSITE_TRANSACTIONS_TIMELINE_FAILURE: 'GET_WEBSITE_TRANSACTIONS_TIMELINE_FAILURE',
}

export const WebsiteTransactionsChannelAction = {
  GET_WEBSITE_TRANSACTIONS_CHANNEL_REQUEST: 'GET_WEBSITE_TRANSACTIONS_CHANNEL_REQUEST',
  GET_WEBSITE_TRANSACTIONS_CHANNEL_SUCCESS: 'GET_WEBSITE_TRANSACTIONS_CHANNEL_SUCCESS',
  GET_WEBSITE_TRANSACTIONS_CHANNEL_FAILURE: 'GET_WEBSITE_TRANSACTIONS_CHANNEL_FAILURE',
}

export const WebsiteTransactionsProductsAction = {
  GET_WEBSITE_TRANSACTIONS_PRODUCTS_REQUEST: 'GET_WEBSITE_TRANSACTIONS_PRODUCTS_REQUEST',
  GET_WEBSITE_TRANSACTIONS_PRODUCTS_SUCCESS: 'GET_WEBSITE_TRANSACTIONS_PRODUCTS_SUCCESS',
  GET_WEBSITE_TRANSACTIONS_PRODUCTS_FAILURE: 'GET_WEBSITE_TRANSACTIONS_PRODUCTS_FAILURE',
}

export const WebsiteGeographicAction = {
  GET_WEBSITE_GEOGRAPHIC_REQUEST: 'GET_WEBSITE_GEOGRAPHIC_REQUEST',
  GET_WEBSITE_GEOGRAPHIC_SUCCESS: 'GET_WEBSITE_GEOGRAPHIC_SUCCESS',
  GET_WEBSITE_GEOGRAPHIC_FAILURE: 'GET_WEBSITE_GEOGRAPHIC_FAILURE',
}

export const GlobalFilterAction = {
  SELECT_GLOBAL_FILTER_START: 'SELECT_GLOBAL_FILTER_START',
  SELECT_GLOBAL_FILTER_DONE: 'SELECT_GLOBAL_FILTER_DONE',
  SELECT_GLOBAL_FILTER_FAILURE: 'SELECT_GLOBAL_FILTER_FAILURE',
}

export const WebsiteBehaviourPillsSelectingAction = {
  SELECT_WEBSITE_BEHAVIOUR_PILLS_START: 'SELECT_WEBSITE_BEHAVIOUR_PILLS_START',
  SELECT_WEBSITE_BEHAVIOUR_PILLS_DONE: 'SELECT_WEBSITE_BEHAVIOUR_PILLS_DONE',
  SELECT_WEBSITE_BEHAVIOUR_PILLS_FAILURE: 'SELECT_WEBSITE_BEHAVIOUR_PILLS_FAILURE',
}

export const WebsiteTransactionsPillsSelectingAction = {
  SELECT_WEBSITE_TRANSACTIONS_PILLS_START: 'SELECT_WEBSITE_TRANSACTIONS_PILLS_START',
  SELECT_WEBSITE_TRANSACTIONS_PILLS_DONE: 'SELECT_WEBSITE_TRANSACTIONS_PILLS_DONE',
  SELECT_WEBSITE_TRANSACTIONS_PILLS_FAILURE: 'SELECT_WEBSITE_TRANSACTIONS_PILLS_FAILURE',
}